line-length = 120

[lint]
select = ["E", "F", "I", "ANN", "N", "ERA"]
ignore = ["ANN101", "ANN102", "ANN401"]

[lint.per-file-ignores]
"trestle-dev-tools_legacy_backend/**" = ["E", "F", "I"]
"trestle-roundhouse-frontend_legacy/**" = ["E", "F", "I"]

[format]
quote-style = "double"
